create table public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

create or replace function public.is_current_user_enabled()
returns boolean
language sql
stable
security definer
set search_path = auth
as $$
  select exists (
    select 1 from auth.users
    where id = auth.uid() and (banned_until is null or banned_until < now())
  );
$$;

create policy "platform admins read user audit log"
  on public.admin_audit_log for select to authenticated
  using (public.is_platform_admin());

create or replace function public.platform_list_users()
returns table (
  user_id uuid,
  email text,
  full_name text,
  app_role text,
  municipality_id uuid,
  email_confirmed boolean,
  last_sign_in_at timestamptz,
  enabled boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_platform_admin() then raise exception 'No autorizado'; end if;
  return query
    select u.id, u.email::text, p.full_name, p.role::text, p.municipality_id,
      u.email_confirmed_at is not null, u.last_sign_in_at,
      coalesce(u.banned_until < now(), true), u.created_at
    from auth.users u
    join public.profiles p on p.id = u.id
    order by u.created_at desc;
end;
$$;

create or replace function public.platform_finalize_user(
  target_email text,
  target_full_name text,
  new_role text,
  target_municipality uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare target_id uuid;
begin
  if not public.is_platform_admin() then raise exception 'No autorizado'; end if;
  if new_role not in ('neighbor', 'driver', 'municipal_admin', 'platform_admin') then raise exception 'Rol inválido'; end if;
  if new_role <> 'platform_admin' and target_municipality is null then raise exception 'El rol requiere un municipio'; end if;
  if target_municipality is not null and not exists (select 1 from public.municipalities where id = target_municipality) then raise exception 'Municipio inexistente'; end if;

  select id into target_id from auth.users where lower(email) = lower(target_email);
  if target_id is null then raise exception 'La cuenta no pudo ser creada en Auth'; end if;

  update auth.users
  set email_confirmed_at = coalesce(email_confirmed_at, now()),
      updated_at = now()
  where id = target_id;

  update public.profiles
  set full_name = coalesce(nullif(target_full_name, ''), full_name),
      role = new_role::public.app_role,
      municipality_id = case when new_role = 'platform_admin' then null else target_municipality end,
      route_id = null,
      updated_at = now()
  where id = target_id;

  insert into public.admin_audit_log(actor_id, target_user_id, action, details)
  values (auth.uid(), target_id, 'user_provisioned', jsonb_build_object('email', target_email, 'role', new_role, 'municipality_id', target_municipality));
  return target_id;
end;
$$;

create or replace function public.platform_set_password(target_user uuid, new_password text)
returns void
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
begin
  if not public.is_platform_admin() then raise exception 'No autorizado'; end if;
  if length(new_password) < 8 then raise exception 'La contraseña debe tener al menos 8 caracteres'; end if;
  if not exists (select 1 from auth.users where id = target_user) then raise exception 'Usuario inexistente'; end if;

  update auth.users
  set encrypted_password = crypt(new_password, gen_salt('bf')),
      recovery_token = '',
      updated_at = now()
  where id = target_user;

  delete from auth.sessions where user_id = target_user;

  insert into public.admin_audit_log(actor_id, target_user_id, action)
  values (auth.uid(), target_user, 'password_changed');
end;
$$;

create or replace function public.platform_set_user_enabled(target_user uuid, user_enabled boolean)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_platform_admin() then raise exception 'No autorizado'; end if;
  if target_user = auth.uid() and not user_enabled then raise exception 'No podés deshabilitar tu propia cuenta'; end if;
  if not exists (select 1 from auth.users where id = target_user) then raise exception 'Usuario inexistente'; end if;

  update auth.users
  set banned_until = case when user_enabled then null else now() + interval '100 years' end,
      updated_at = now()
  where id = target_user;

  if not user_enabled then
    delete from auth.sessions where user_id = target_user;
  end if;

  insert into public.admin_audit_log(actor_id, target_user_id, action)
  values (auth.uid(), target_user, case when user_enabled then 'user_enabled' else 'user_disabled' end);
end;
$$;

create or replace function public.platform_update_user_access(target_user uuid, new_role text, target_municipality uuid default null)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_platform_admin() then raise exception 'No autorizado'; end if;
  if target_user = auth.uid() and new_role <> 'platform_admin' then raise exception 'No podés quitarte tu propio acceso de plataforma'; end if;
  if new_role not in ('neighbor', 'driver', 'municipal_admin', 'platform_admin') then raise exception 'Rol inválido'; end if;
  if new_role <> 'platform_admin' and target_municipality is null then raise exception 'El rol requiere un municipio'; end if;

  update public.profiles
  set role = new_role::public.app_role,
      municipality_id = case when new_role = 'platform_admin' then null else target_municipality end,
      route_id = null,
      updated_at = now()
  where id = target_user;
  if not found then raise exception 'Usuario inexistente'; end if;

  insert into public.admin_audit_log(actor_id, target_user_id, action, details)
  values (auth.uid(), target_user, 'access_changed', jsonb_build_object('role', new_role, 'municipality_id', target_municipality));
end;
$$;

revoke all on function public.platform_list_users() from public;
revoke all on function public.platform_finalize_user(text, text, text, uuid) from public;
revoke all on function public.platform_set_password(uuid, text) from public;
revoke all on function public.platform_set_user_enabled(uuid, boolean) from public;
revoke all on function public.platform_update_user_access(uuid, text, uuid) from public;
revoke all on function public.is_current_user_enabled() from public;

grant execute on function public.platform_list_users() to authenticated;
grant execute on function public.platform_finalize_user(text, text, text, uuid) to authenticated;
grant execute on function public.platform_set_password(uuid, text) to authenticated;
grant execute on function public.platform_set_user_enabled(uuid, boolean) to authenticated;
grant execute on function public.platform_update_user_access(uuid, text, uuid) to authenticated;
grant execute on function public.is_current_user_enabled() to authenticated;
grant select on public.admin_audit_log to authenticated;

create policy "enabled users only" on public.municipalities as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.profiles as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.routes as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.vehicles as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.route_stops as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.route_assignments as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.route_runs as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.vehicle_locations as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.notification_settings as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.push_subscriptions as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.alerts as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
create policy "enabled users only" on public.admin_audit_log as restrictive for all to authenticated
  using (public.is_current_user_enabled()) with check (public.is_current_user_enabled());
